# Generated by Django 5.0.2 on 2024-05-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
    ]
