# Generated by Django 5.0.2 on 2024-05-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
