# Generated by Django 5.0.2 on 2024-05-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "messenger",
            "0002_alter_channel_managers_alter_channelmessage_managers_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="channelmessage",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="channeluser",
            name="is_active",
        ),
    ]
