# Generated by Django 5.0.2 on 2024-05-24 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0004_alter_channelmessage_sender_channel_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelmember",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="messenger.channel",
            ),
        ),
    ]
